---

- name: Update the application to the latest version
  hosts: "{{ target|default('staging') }}"
  remote_user: "{{ application_user }}"
  roles:
    - env
    - npm
    - django
    - supervisor
    - {role: nginx, remote_user: root}
