---

- name: Update the application to the latest version
  hosts: "{{ target|default('staging') }}"
  remote_user: "{{ application_user }}"
  roles:
    - env
    - npm
    - django
    - supervisor

- name: Update nginx config
  hosts: "{{ target|default('staging') }}"
  remote_user: root
  roles:
    - nginx
