---

- name: Provision the server with all required packages and user accounts
  hosts: "{{ target|default('staging') }}"
  remote_user: root
  roles:
    - users
    - base
    - postgres
    - nginx
