---

- name: Ensure environment file directory exists
  file: name={{ env_dir }} state=directory mode=0700 owner={{ application_user }}

- name: Copy the environment variables file
  template: src="{{ item.src }}"
            dest="{{ item.dest }}"
            owner={{ application_user }}
            group={{ application_user }}
            mode=0700
  with_items:
    - {dest: "{{ env_file_dest }}", src: "env.txt.j2"}
    - {dest: "{{ env_file_dest_bash }}", src: "env-bash.txt.j2"}
