---
# Creates the database for the application

- name: Create application database user
  postgresql_user: name={{ db_user }}
                   password={{ db_password }}
                   role_attr_flags=NOCREATEDB,NOSUPERUSER,NOCREATEROLE
  become: yes
  become_user: postgres

- name: Create application database
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 owner={{ db_user }}
  become: yes
  become_user: postgres

- name: Allow local (unix socket) password access
  lineinfile: dest="{{ pg_data_dir }}pg_hba.conf"
              line="local   {{ db_name }}    {{ db_user }}    md5"
              insertbefore="^# \"local\" is for Unix domain socket connections only"
  notify:
    - reload postgres

- name: Allow IPv4 (tcp) password access
  lineinfile: dest="{{ pg_data_dir }}pg_hba.conf"
              line="host    {{ db_name }}    {{ db_user }}  127.0.0.1/32  md5"
              insertbefore="^# IPv6 local connections"
  notify:
    - reload postgres
